### ISSUE TITLE
1.3.5 update results in ResourceClosedError's in unit tests

### ISSUE THREAD

**Issue by rgeens** [kvesteri/sqlalchemy-continuum#188] opened 2018-06-04 12:17 UTC
Has the cloned connection functionality from 1.3.5 introduced additional constraints on what you're allowed to do with connections? I had the unit tests in my Gitlab pipelines fail across multiple projects after the update to 1.3.5. ~~It didn't reproduce when running the tests locally.~~ It also reproduces locally.

```
Traceback (most recent call last):
  File "/usr/local/lib/python3.5/site-packages/sqlalchemy/orm/session.py", line 2344, in _flush
    flush_context.execute()
  File "/usr/local/lib/python3.5/site-packages/sqlalchemy/orm/unitofwork.py", line 391, in execute
    rec.execute(self)
  File "/usr/local/lib/python3.5/site-packages/sqlalchemy/orm/unitofwork.py", line 556, in execute
    uow
  File "/usr/local/lib/python3.5/site-packages/sqlalchemy/orm/persistence.py", line 181, in save_obj
    mapper, table, insert)
  File "/usr/local/lib/python3.5/site-packages/sqlalchemy/orm/persistence.py", line 865, in _emit_insert_statements
    result = cached_connections[connection].\
  File "/usr/local/lib/python3.5/site-packages/sqlalchemy/util/_collections.py", line 729, in __missing__
    self[key] = val = self.creator(key)
  File "/usr/local/lib/python3.5/site-packages/sqlalchemy/orm/persistence.py", line 1268, in <lambda>
    compiled_cache=base_mapper._compiled_cache
  File "/usr/local/lib/python3.5/site-packages/sqlalchemy/engine/base.py", line 317, in execution_options
    self.dispatch.set_connection_execution_options(c, opt)
  File "/usr/local/lib/python3.5/site-packages/sqlalchemy/event/attr.py", line 284, in __call__
    fn(*args, **kw)
  File "/usr/local/lib/python3.5/site-packages/sqlalchemy_continuum/manager.py", line 412, in track_cloned_connections
    if connection.connection is c.connection:  # ConnectionFairy is the same - this is a clone
  File "/usr/local/lib/python3.5/site-packages/sqlalchemy/engine/base.py", line 354, in connection
    self._handle_dbapi_exception(e, None, None, None, None)
  File "/usr/local/lib/python3.5/site-packages/sqlalchemy/engine/base.py", line 1416, in _handle_dbapi_exception
    util.reraise(*exc_info)
  File "/usr/local/lib/python3.5/site-packages/sqlalchemy/util/compat.py", line 187, in reraise
    raise value
  File "/usr/local/lib/python3.5/site-packages/sqlalchemy/engine/base.py", line 352, in connection
    return self._revalidate_connection()
  File "/usr/local/lib/python3.5/site-packages/sqlalchemy/engine/base.py", line 432, in _revalidate_connection
    raise exc.ResourceClosedError("This Connection is closed")
sqlalchemy.exc.ResourceClosedError: This Connection is closed
```

The error seems to be happening while a pytest fixture is being setup, adding some objects to a session and committing them. I'll try and spend some more time later to get a reproducible test case.

**Comment by rgeens** [comment] 2018-06-04 16:14
It reproduces when running a suite of tests or even a single module with multiple tests, but it doesn't when running the failed tests individually. I suspect there might be an interaction with how pytest parallelizes tests.

**Comment by zzacharo** [comment] 2018-06-08 08:29
Any progress with this?

**Comment by rgeens** [comment] 2018-06-09 16:15
I've been able to reproduce the issue. Run pytest on this:
```python
import pytest
from flask import Flask
from flask_sqlalchemy import SQLAlchemy
from sqlalchemy import Column, Integer, String
from sqlalchemy_continuum import make_versioned
from sqlalchemy_continuum.plugins import FlaskPlugin

db = SQLAlchemy()


class Dummy(db.Model):
    __tablename__ = 'dummy'
    id = Column(Integer, primary_key=True)
    name = Column(String)


@pytest.fixture(scope='function')
def app(request):
    class Config:
        DEBUG = True
        TESTING = True
        SQLALCHEMY_DATABASE_URI = 'sqlite:///:memory:'

    app = Flask('continuum-resourceclosederror')
    app.config.from_object(Config)
    db.init_app(app)
    make_versioned(plugins=[FlaskPlugin()])

    with app.app_context():
        db.create_all()
        yield app


@pytest.fixture
def session(app):
    with app.app_context():
        yield db.session


@pytest.fixture
def dummy(session):
    obj = Dummy(name='test')
    session.add(obj)
    session.commit()
    return obj


class TestClass:
    def test_succeeds(self, session, dummy):
        # Both lines need to be present for the issue to reproduce
        session.delete(dummy)
        assert Dummy.query.count() == 0

    def test_raises_error(self, dummy):
        assert True

```

The corresponding requirements.txt is:
```
atomicwrites==1.1.5
attrs==18.1.0
click==6.7
Flask==1.0.2
Flask-SQLAlchemy==2.3.2
itsdangerous==0.24
Jinja2==2.10
MarkupSafe==1.0
more-itertools==4.2.0
pluggy==0.6.0
py==1.5.3
pytest==3.6.1
six==1.11.0
SQLAlchemy==1.2.8
SQLAlchemy-Continuum==1.3.5
SQLAlchemy-Utils==0.33.3
Werkzeug==0.14.1
```

**Comment by kvesteri** [comment] 2018-06-12 16:36
@netcriptus are you aware of this problem? Your merged PR for tracking cloned connections caused this.

**Comment by patvdleer** [comment] 2018-06-13 09:32
Can confirm, I have the same issues with this.

**Comment by rgeens** [comment] 2018-07-01 17:54
I've spent some time debugging this and while the tracking cloned connections change triggers the error, it doesn't seem to be the underlying cause.

The exception occurs because `VersioningManager.session_connection_map` state persists across unit tests. There's old closed connections in there that aren't cleared out, and so when then the cloned connection tracking iterates over it the `ResourceClosedError` exception happens.

That state bleed-over also happens before 1.3.5. Continuum uses `VersioningManager.clear` to remove closed connections in response to `after_commit` and `after_rollback` events. However, this leaves at least one case out: commits (and subsequent connection closes) that happens as a part of transactions triggered by flushes.

I'll give an example based on my test case above. What happens in the `dummy` fixture is the normal case: `session.commit` is called, which close the connection, which is removed from `session_connection_map` by `clear` in response to an `after_commit` event.

The trouble occurs in `test_succeeds`. First `session.delete` dirties the session. When `count` is called, it flushes those changes to the database using a new connection (which gets registered in `session_connection_map`). It does that by calling `commit` on a `SessionTransaction`, which also closes said connection. The event associated with that is `after_transaction_end`, there's no `after_commit` involved. As a result `session_connection_map` doesn't get updated as it should.

So it looks like the fix would involve calling `clear` appropriately when `after_transaction_end` happens. At the moment I can't tell yet what the impact of that would be and whether the behavior is the same for non-sqlite databases, so that would require further investigation.

**Comment by rgeens** [comment] 2018-07-14 19:00
Having attempted a fix, I think I got the closing of transactions and connections mixed up. I had made the assumption that the connection that triggers the error got closed after the `flush` resulting from the `count` call, which would mean that the `session_connection_map` should be empty after that like in https://github.com/kvesteri/sqlalchemy-continuum/pull/194/commits/ddbf061ce5aea28cb1b0305d03bd382bfaab000a .

But this is not the case, it was just the transaction that got closed. The connection stays active after the `count` call and that's fine. The actual closing happens in the test teardown, which continuum isn't aware of at the moment. So I'll look into either reacting to that or to simply purging closed connections from the `session_connection_map` if they're detected.

**Comment by rgeens** [comment] 2018-07-15 12:35
The way continuum's own unit tests do it, is call `versioning_manager.reset()` in the teardown. The docstring for `reset` says:

> Resets this manager's internal state.
>
>        This method should be used in test cases that create models on the fly.
>        Otherwise history_class_map and some other variables would be polluted
>        by no more used model classes.

My own code is currently not doing that, resulting in the mentioned pollution.

My connections are closed when the `app.app_context` exits. Flask emits a `appcontext_tearing_down` signal while doing this. I'm going to try and see if I can use the FlaskPlugin to reset the versioning manager in response to Flask app context teardowns.

**Comment by rgeens** [comment] 2018-07-15 13:11
https://github.com/kvesteri/sqlalchemy-continuum/issues/45 implies that if `make_versioned` is called in a unit test, `remove_versioning` should be called to cleanup, which is wider in scope than just `versioning_manager.reset`.

**Comment by rgeens** [comment] 2018-07-15 13:39
For the 4 years since https://github.com/kvesteri/sqlalchemy-continuum/issues/45 was added, it seems there wasn't specifically anything obligating people to use `remove_versioning` in unit tests, since things would mostly just work (unless you were doing something specific with versions in the test I suppose). The addition of the cloned connection tracking triggered everybody who had the state pollution resulting from not calling `remove_versioning`.

Perhaps `make_versioned` should throw an exception or even call `remove_versioning` if it detects it was called before?

**Comment by rgeens** [comment] 2018-07-15 14:13
Or add a context manager for use in tests.

**Comment by vault** [comment] 2018-07-26 20:11
From what I can tell the problem is that sqlalchemy-continuum isn't catching rollback events when they're not being emitted by the session (for instance, the external transaction a session is bound to in a test-suite gets rolled back). This results in `VersioningManager` leaking connection info in `units_of_work` and `session_connection_map`. Later with new sessions it iterates over connections it knows about to look for cloned connections. This tries to access `connection.connection` which will generate the `ResourceClosedError` if the connection happens to be closed. In this case those connections are closed since they were leaked from the previous session.

I think I've been able to fix this by listening for engine rollback events. I'll open a PR.

**Closed** 2018-07-30 12:44 UTC

**Comment by rgeens** [comment] 2018-07-30 13:12
Cool, I can confirm this fixes the issue in my test case. I didn't know engine rollback events were a thing. Thanks @vault !
